openapi: 3.2.0
info:
  title: People Service Get Organizations By Identifier API
  version: 0.0.1
servers:
- url: /api/v1
security:
- apiKey: []
tags:
- name: Get Organizations By Identifier
paths:
  /get-organizations-by-identifier:
    post:
      summary: Get organization records by one of the extra identifiers
      operationId: GetOrganizationsByIdentifier
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetOrganizationsByIdentifierRequest'
        required: true
      responses:
        '200':
          description: Retrieve a organization records successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationListResponse'
        default:
          $ref: '#/components/responses/Error'
      tags:
      - Get Organizations By Identifier
components:
  schemas:
    GetOrganizationsByIdentifierRequest:
      type: object
      properties:
        identifier:
          type: array
          items:
            type: string
            minLength: 1
            pattern: ^urn:(gismo_id|ugent_id|biblio_id|ugent_memorialis_id):.+
      required:
      - identifier
    Organization:
      type: object
      properties:
        id:
          type: string
        date_created:
          type: string
          format: date-time
        date_updated:
          type: string
          format: date-time
        type:
          type: string
        acronym:
          type: string
        name_dut:
          type: string
        name_eng:
          type: string
        parent:
          type: array
          items:
            $ref: '#/components/schemas/OrganizationParent'
        identifier:
          type: array
          items:
            type: string
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int64
        message:
          type: string
      required:
      - code
      - message
    OrganizationParent:
      type: object
      properties:
        id:
          type: string
        date_created:
          type: string
          format: date-time
        date_updated:
          type: string
          format: date-time
        from:
          type: string
          format: date-time
        until:
          type: string
          format: date-time
      required:
      - id
      - from
    OrganizationListResponse:
      type: object
      required:
      - data
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Organization'
  responses:
    Error:
      description: Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: X-Api-Key
