openapi: 3.2.0
info:
  title: People Service Set Person Role API
  version: 0.0.1
servers:
- url: /api/v1
security:
- apiKey: []
tags:
- name: Set Person Role
paths:
  /set-person-role:
    post:
      summary: Update person role
      operationId: SetPersonRole
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SetPersonRoleRequest'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        default:
          $ref: '#/components/responses/Error'
      tags:
      - Set Person Role
components:
  schemas:
    SetPersonRoleRequest:
      type: object
      properties:
        id:
          type: string
          minLength: 1
        role:
          type: array
          items:
            type: string
            minLength: 1
      required:
      - id
      - role
    StringMap:
      type: object
      additionalProperties:
        type: string
    Person:
      type: object
      properties:
        id:
          type: string
        active:
          type: boolean
        date_created:
          type: string
          format: date-time
        date_updated:
          type: string
          format: date-time
        name:
          type: string
        given_name:
          type: string
        family_name:
          type: string
        email:
          type: string
        token:
          $ref: '#/components/schemas/StringMap'
        preferred_given_name:
          type: string
        preferred_family_name:
          type: string
        birth_date:
          type: string
        honorific_prefix:
          type: string
        identifier:
          type: array
          items:
            type: string
        organization:
          type: array
          items:
            $ref: '#/components/schemas/OrganizationMember'
        job_category:
          type: array
          items:
            type: string
        role:
          type: array
          items:
            type: string
        settings:
          type: object
          additionalProperties:
            type: string
        object_class:
          type: array
          items:
            type: string
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int64
        message:
          type: string
      required:
      - code
      - message
    OrganizationMember:
      type: object
      properties:
        id:
          type: string
        date_created:
          type: string
          format: date-time
        date_updated:
          type: string
          format: date-time
      required:
      - id
  responses:
    Error:
      description: Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: X-Api-Key
